# File beat configuration to copy logs from web servers, to a specific kafka topic (nginx_logs)
- type: filestream
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/*.log
	
#Disable elasticsearch and add the following
#======== Processors ==========
output.kafka:
  hosts: ["localhost:9092"]
  topic: "nginx_logs"
  codec.json:
   pretty: false
